# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 13 Mar 2017 08:34:56 +0000
*               @ALL          0
*               @user         8
