<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: helena
 * Date: Tue, 14 Mar 2017 13:48:12 +0000
 */

$conf['title'] = 'Linkit Vostok Team Wiki';
$conf['template'] = 'codowik-master';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['jquerycdn'] = '0';

// end auto-generated content
