<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: helena
 * Date: Mon, 13 Mar 2017 08:52:37 +0000
 */

$conf['title'] = 'Linkit Vostok Team Wiki';
$conf['template'] = 'codowik-master';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
